### ISSUE TITLE
Does not work anylonger

### ISSUE THREAD

**Issue by atoou-team1** [bazelbuild/examples#10]
With your files:

bazel build //backend:backend 
ERROR: /home/<xxxx>/projects/bazel_examples_source/tutorial/backend/BUILD:14:1: every rule of type appengine
_war implicitly depends upon the target '@commons-lang//jar:jar', but this target could not be found because of: no
 such package '@commons-lang//jar': error loading package 'external': The repository named 'commons-lang' could not
 be resolved.
ERROR: Loading failed; build aborted.

Following the instructions of the tutorial:

bazel build //backend:backend
ERROR: /home/<xxx>/projects/bazel_examples_source/tutorial/WORKSPACE:12:1: appengine-java is not a legal workspace name.
ERROR: /home/<xxx>/projects/bazel_examples_source/tutorial/WORKSPACE:34:1: commons-lang is not a legal workspace name.
ERROR: /home/<xxx>/projects/bazel_examples_source/tutorial/WORKSPACE:39:1: javax-servlet-api is not a legal workspace name.
ERROR: Error evaluating WORKSPACE file.
ERROR: no such package 'external': Package 'external' contains errors.

**Comment by kchodorow** [comment]
It sounds like you're using a combination of a new version of Bazel with an old version of the tutorial.  Could you pull the latest version of the tutorial code and try again?

**Comment by atoou-team1** [comment]
If anything, it seems that the tutorial is using an old version of bazel ;)
I pulled the tutorial 2 days ago when I tried it, there has be no commit since 6 days.
Also that is the tutorial 'ready' code, the other part that also does not work is the tutorial copy-paste code in the tutorial docs.

I've been trying to fix it myself with no luck yet. The tutorial for building android works, but it seems the appengine tutorial is really in bad shape.

**Comment by ahumesky** [comment]
The commit that renames everything in the tutorial to remove dashes is here:
https://github.com/bazelbuild/examples/commit/0d5ab883e75e6a2a45c476cb289498a04178ad0e

So the tutorial here:
https://github.com/bazelbuild/examples/tree/master/tutorial
should be up to date.

It does look like the docs need to be updated to use underscores instead of dashes though:
http://bazel.io/docs/tutorial/backend-server.html

**Comment by ahumesky** [comment]
Fixed here:
https://github.com/bazelbuild/bazel/commit/50ebf2a4a3554414993b37612188e9ebd478e1ff

**Comment by atoou-team1** [comment]
The master is now working, but the instructions in the tutorial are still wrong.
The doc says
load("/tools/build_rules/appengine/appengine", "appengine_war")

but this only works as
load("@bazel_tools//tools/build_rules/appengine:appengine.bzl", "appengine_war")

diff is '@bazel_tools' and ':appengine.bzl'

Also in WORKSPACE the doc says:

bind(
    name = "javax/servlet/api",
    actual = "//tools/build_rules/appengine:javax.servlet.api",
)

while what you have in the master branch works:

bind(
    name = "javax/servlet/api",
    actual = "@bazel_tools//tools/build_rules/appengine:javax.servlet.api",
)

(diff is missing "@bazel_tools" in 'actual' field)
